// Auto-generated by LibreLane
module lstm16x_top(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input clk,
  input rst_n,
  input cmd_valid,
  input[7:0] cmd_data,
  output rsp_valid,
  output[7:0] rsp_data
);
endmodule
